### ISSUE TITLE
Project list with missing `\n`

### ISSUE THREAD

**Issue by shym** [tarides/okra#137]
Given the following `conf.yaml`:

```
projects:
  - title: "Project 1 (#1)"
  - title: "Project 2 (#2)"
  - title: "Project 3 (#3)"
  - title: "Project 4 (#4)"
```

`okra generate --conf=conf.yaml` produces:

```
...
# Projects

- Project 1 (#1)
- Project 2 (#2)- Project 3 (#3)
- Project 4 (#4)

# Last Week
...
```

where 2 and 3 are joined on the same line.
